# VirtualService defines how requests are routed to services within the mesh.
# VirtualServices allow you to configure advanced traffic routing rules, such as traffic splitting, retries, timeouts, and fault injection.

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
    - "*" # Applies to all hosts
  gateways:
    - calc-gateway # Uses the 'bookinfo-gateway' defined above
  http:
    - route:
        - destination:
            host: calc
            port:
              number: 5000
