apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: production
  labels:
    app: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: yagneshjariwala/login:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: prod-cm
