apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: production
spec:
  selector:
    app: login
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 30500
    targetPort: 30500
    nodePort: 30500
